# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190325_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image_image', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Category')),
                ('editor', models.ManyToManyField(null=True, to='photos.Editor')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='article',
            name='location',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
