# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 13:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20190329_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('content', models.TextField(verbose_name='Comment')),
                ('pub_date', models.DateTimeField(verbose_name='Date of comment')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Image')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.RenameModel(
            old_name='Editor',
            new_name='User',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.User'),
        ),
    ]
